[23-Apr-21 06:03:44] INFO       | discord.client: logging in using static token
[23-Apr-21 06:03:44] INFO       | discord.gateway: Shard ID None has sent the IDENTIFY payload.
[23-Apr-21 06:03:44] INFO       | discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-main-s9tk",{"micros":192756,"calls":["discord-sessions-prd-2-155",{"micros":189492,"calls":["start_session",{"micros":29204,"calls":["api-prd-main-kx59",{"micros":26545,"calls":["get_user",{"micros":2550},"add_authorized_ip",{"micros":1286},"get_guilds",{"micros":7611},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":30,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 79e565559d103782f8491fcfe96d3f5a).
[23-Apr-21 06:03:50] WARNING    | root      : Logged in as Groot#2676, SQLite3 database initialized.
[23-Apr-21 06:09:23] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30d1140d00>
[23-Apr-21 06:14:05] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbd7ff10>
[23-Apr-21 06:15:31] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbc173d0>
[23-Apr-21 06:17:07] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbaceeb0>
[23-Apr-21 06:37:16] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbc98670>
[23-Apr-21 06:38:05] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbac1370>
[23-Apr-21 06:42:17] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbc63d30>
[23-Apr-21 06:56:34] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bb8ca3a0>
[23-Apr-21 06:56:34] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-6417' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 06:57:37] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bba9cbb0>
[23-Apr-21 06:58:03] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30d3bbe7f0>
[23-Apr-21 06:58:20] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bba57160>
[23-Apr-21 06:59:19] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbe0d8e0>
[23-Apr-21 06:59:34] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbe1e070>
[23-Apr-21 07:10:35] INFO       | discord.gateway: Websocket closed with 1006, attempting a reconnect.
[23-Apr-21 07:10:35] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 07:10:35] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 07:10:35] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-gztf",{"micros":4666,"calls":["discord-sessions-prd-2-155",{"micros":40}]}].
[23-Apr-21 07:13:07] ERROR      | asyncio   : Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f30bbd701f0>
[23-Apr-21 09:17:52] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 09:17:52] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 09:17:52] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-j7zt",{"micros":2656,"calls":["discord-sessions-prd-2-155",{"micros":23}]}].
[23-Apr-21 11:42:40] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 11:42:40] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 11:42:40] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-v2qn",{"micros":1757,"calls":["discord-sessions-prd-2-155",{"micros":105}]}].
[23-Apr-21 12:23:17] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 12:23:17] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 12:23:17] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-52rx",{"micros":1957,"calls":["discord-sessions-prd-2-155",{"micros":24}]}].
[23-Apr-21 16:13:54] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 16:13:54] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 16:13:54] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-54tx",{"micros":3458,"calls":["discord-sessions-prd-2-155",{"micros":52}]}].
[23-Apr-21 16:29:38] INFO       | discord.gateway: Websocket closed with 1006, attempting a reconnect.
[23-Apr-21 16:29:38] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 16:29:39] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 16:29:39] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-1pqt",{"micros":5741,"calls":["discord-sessions-prd-2-155",{"micros":135}]}].
[23-Apr-21 17:16:02] INFO       | discord.gateway: Websocket closed with 1006, attempting a reconnect.
[23-Apr-21 17:16:02] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 17:16:02] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 17:16:02] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-52rx",{"micros":2282,"calls":["discord-sessions-prd-2-155",{"micros":154}]}].
[23-Apr-21 18:14:43] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 18:14:43] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 18:14:43] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-vf9c",{"micros":1418,"calls":["discord-sessions-prd-2-155",{"micros":43}]}].
[23-Apr-21 19:22:11] INFO       | discord.gateway: Websocket closed with 1006, attempting a reconnect.
[23-Apr-21 19:22:11] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 19:22:11] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 19:22:11] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-mmh4",{"micros":1332,"calls":["discord-sessions-prd-2-155",{"micros":66}]}].
[23-Apr-21 19:45:31] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 19:45:31] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 19:45:31] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-zrkf",{"micros":13138,"calls":["discord-sessions-prd-2-155",{"micros":46}]}].
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-5610' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-5477' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-1973' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-1459' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-1733' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:00:04] ERROR      | asyncio   : Task exception was never retrieved
future: <Task finished name='Task-745' coro=<Loop._loop() done, defined at /home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py:88> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
    raise exc
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/container/GrootDiscordBot/cogs/core.py", line 104, in loops
    for user in self.bot.cached_users:
TypeError: 'NoneType' object is not iterable
[23-Apr-21 22:57:29] INFO       | discord.client: Got a request to RESUME the websocket.
[23-Apr-21 22:57:29] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[23-Apr-21 22:57:29] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-7p4k",{"micros":1052,"calls":["discord-sessions-prd-2-155",{"micros":20}]}].
[24-Apr-21 00:56:37] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 00:56:37] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 00:56:37] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-t7cp",{"micros":3009,"calls":["discord-sessions-prd-2-155",{"micros":49}]}].
[24-Apr-21 04:30:38] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 04:30:38] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 04:30:38] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-shd1",{"micros":1176,"calls":["discord-sessions-prd-2-155",{"micros":31}]}].
[24-Apr-21 04:51:40] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 04:51:41] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 04:51:41] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-77sw",{"micros":2824,"calls":["discord-sessions-prd-2-155",{"micros":27}]}].
[24-Apr-21 07:00:44] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 07:00:44] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 07:00:44] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-s9tk",{"micros":5923,"calls":["discord-sessions-prd-2-155",{"micros":88}]}].
[24-Apr-21 10:14:47] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 10:14:47] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 10:14:47] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-qmnl",{"micros":772,"calls":["discord-sessions-prd-2-155",{"micros":39}]}].
[24-Apr-21 10:47:10] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 10:47:10] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 10:47:10] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-84mn",{"micros":3617,"calls":["discord-sessions-prd-2-155",{"micros":35}]}].
[24-Apr-21 14:38:29] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 14:38:29] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 14:38:29] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-01fw",{"micros":4286,"calls":["discord-sessions-prd-2-155",{"micros":54}]}].
[24-Apr-21 17:08:12] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 17:08:12] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 17:08:12] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-s9tk",{"micros":1206,"calls":["discord-sessions-prd-2-155",{"micros":26}]}].
[24-Apr-21 17:27:12] INFO       | discord.gateway: Timed out receiving packet. Attempting a reconnect.
[24-Apr-21 17:27:12] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 17:27:13] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 17:27:13] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-ctl8",{"micros":21526,"calls":["discord-sessions-prd-2-155",{"micros":758}]}].
[24-Apr-21 19:55:23] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 19:55:23] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 19:55:23] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-747h",{"micros":1537,"calls":["discord-sessions-prd-2-155",{"micros":54}]}].
[24-Apr-21 21:25:55] INFO       | discord.client: Got a request to RESUME the websocket.
[24-Apr-21 21:25:55] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[24-Apr-21 21:25:55] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-1643",{"micros":12075,"calls":["discord-sessions-prd-2-155",{"micros":105}]}].
[25-Apr-21 01:21:03] INFO       | discord.client: Got a request to RESUME the websocket.
[25-Apr-21 01:21:03] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[25-Apr-21 01:21:03] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-r84b",{"micros":10811,"calls":["discord-sessions-prd-2-155",{"micros":146}]}].
[25-Apr-21 02:38:26] INFO       | discord.client: Got a request to RESUME the websocket.
[25-Apr-21 02:38:26] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[25-Apr-21 02:38:26] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-ztzb",{"micros":3253,"calls":["discord-sessions-prd-2-155",{"micros":20}]}].
[25-Apr-21 05:27:06] INFO       | discord.client: Got a request to RESUME the websocket.
[25-Apr-21 05:27:06] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[25-Apr-21 05:27:06] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-lz1z",{"micros":440,"calls":["discord-sessions-prd-2-155",{"micros":35}]}].
[25-Apr-21 07:35:20] INFO       | discord.client: Got a request to RESUME the websocket.
[25-Apr-21 07:35:20] INFO       | discord.gateway: Shard ID None has sent the RESUME payload.
[25-Apr-21 07:35:20] INFO       | discord.gateway: Shard ID None has successfully RESUMED session 79e565559d103782f8491fcfe96d3f5a under trace ["gateway-prd-main-r3ld",{"micros":6919,"calls":["discord-sessions-prd-2-155",{"micros":49}]}].
